# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=80)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('url_resource', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
