# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlshort',
            old_name='url_resource',
            new_name='url',
        ),
    ]
